

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Test 
      run: |
        python sample.py
        
        
        
        - name: Unit Testing With Python
        
  # You may pin to the exact commit or the version.
  # uses: PrajjawalBanati/Python-actions@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
  uses: PrajjawalBanati/Python-actions@0.0.1
  with:
    # Always push your code and test case file as name.py and test_name.py
    src: # optional
        
        
        
        
  
        



      
       
        
 
      
