name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Test 
      run: |
        python sample.py
       
  unittest:
   needs: [build]
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 

    - name: unittest
      run: |
        python sample.py
        

  package:

    runs-on: ubuntu-latest
    needs: [unittest]
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
     

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Test with pytest
      run: |
        python sample.py
        
        
        
      
      
      
Deployment

jobs:
needs: [ package ]
    deployment:
      runs-on: ubuntu-latest
      environment: 
        name: production
        url: https://github.com
      steps:
        - name: deploy
        run: |
        python sample.py

        
 




 























  
   
        
        
  
        



      
       
        
 
      
